[package]
name = "actix-form-data"
description = "Multipart Form Data for Actix Web"
version = "0.2.1"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://github.com/asonix/actix-multipart"
readme = "README.md"
keywords = ["actix", "form-data", "multipart", "async"]

[lib]
name = "form_data"

[dependencies]
actix = "0.5.6"
actix-web = "0.6.0"
bytes = "0.4.7"
failure = "0.1"
futures = "0.1.21"
futures-cpupool = "0.1.8"
futures-fs = "0.0.4"
http = "0.1.5"
log = "0.4.1"
mime = "0.3.5"

[dev-dependencies]
env_logger = "0.5.9"
serde = "1.0"
serde_derive = "1.0"
